name: ongi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  email_validator: ^2.1.17
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  align_positioned: ^5.0.1
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/nav_Home.svg
    - assets/images/nav_Health.svg
    - assets/images/nav_Commun.svg
    - assets/images/nav_Mypage.svg
    - assets/images/pill_history_title_logo.png
    - assets/images/pill_item_icon.svg
    - assets/images/add_icon.svg
    - assets/images/ruler_icon.svg
    - assets/images/parent_exercise_icon.png
    - assets/images/sitting_mom_icon.png
    - assets/images/step_tracker_title_logo.png
    - assets/images/homebar_capsule.svg
    - assets/images/homebar_med.svg
    - assets/images/homebar_walk.svg
    - assets/images/walk_icon.svg
    - assets/images/users/elderly_woman.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
