name: ongi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  email_validator: ^2.1.17
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  align_positioned: ^5.0.1
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_charts: ^0.5.2
  fl_chart: ^1.0.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  camera: ^0.11.2
  flutter_neumorphic_plus: ^3.5.0
  body_part_selector: ^0.2.0
  flutter_svg: any
  path_drawing: ^1.0.1
  interactable_svg: ^0.0.7
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.2.1
  flutter_local_notifications: ^19.4.0
  health: ^13.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/logo_white.svg
    - assets/images/nav_Home.svg
    - assets/images/nav_Health.svg
    - assets/images/nav_Commun.svg
    - assets/images/nav_Mypage.svg
    - assets/images/pill_history_title_logo.png
    - assets/images/pill_item_icon.svg
    - assets/images/splash_icon.svg
    - assets/images/splash_icon.png
    - assets/images/add_icon.svg
    - assets/images/ruler_icon.svg
    - assets/images/parent_exercise_icon.png
    - assets/images/sitting_mom_icon.png
    - assets/images/step_tracker_title_logo.png
    - assets/images/homebar_capsule.svg
    - assets/images/homebar_med.svg
    - assets/images/homebar_walk.svg
    - assets/images/exercise_record_title_logo.png
    - assets/images/walk_icon.svg
    - assets/images/users/elderly_woman.png
    - assets/images/close_icon_orange.svg
    - assets/images/reward_icon.svg
    - assets/images/reward_gift_icon.png
    - assets/images/all_pfp_icons.png
    - assets/images/photobook_icon.png
    - assets/images/reward_products/
    - assets/images/users/
    - assets/images/close_icon_black.svg
    - assets/images/close_icon_white.svg
    - assets/images/back_icon_black.svg
    - assets/images/back_icon_white.svg
    - assets/images/dropdown_icon.svg
    - assets/images/camera_button.svg
    - assets/images/step_tracker_crown.svg
    - assets/images/step_tracker_light_background.svg
    - assets/images/step_tracker_rectangle.svg
    - assets/images/sample_family_photo.png
    - assets/images/body_front.png
    - assets/images/body_front_btn.png
    - assets/images/body_back.png
    - assets/images/body_back_btn.png
    - assets/images/speech_bubble.png
    - assets/images/body_selector_front.svg
    - assets/images/body_selector_back.svg
    - assets/images/location_icon.svg
    - assets/images/record_tooltip.svg
    - assets/images/cross_family_ranking_title_logo.png
    - assets/images/step_ranking_icon.svg
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900